### ISSUE TITLE
Universal Deployment with CREATE2

### ISSUE THREAD

**Issue by Ro5s** [WETH10/WETH10#14]
Another no brainer in the wETH upgrade contract would be a way to take advantage of CREATE2 method to allow users to associate an address with 'wrapping ether' regardless of chainID.

**Comment by Ro5s** [comment]
I figure we can just use this like Uniswap fam https://eips.ethereum.org/EIPS/eip-1014 Will try and knock out over weekend

**Comment by Ro5s** [comment]
Prob should just use this? https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Create2.sol

**Comment by Ro5s** [comment]
Helpful guide from OZ with example deployment (sending eth to precomputed address, then deploying vault contract to claim ether at same address): https://docs.openzeppelin.com/cli/2.8/deploying-with-create2 I should have time tmrw to test and make PR 🔧

**Comment by Ro5s** [comment]
@abcoathup do you have a quick sense of how easy / tricksy it might be to use the OZ Create2.sol to implement for wETH? :raised_hands:

**Comment by abcoathup** [comment]
Hi @Ro5s, 

I assume you are deploying a regular contract (rather than an upgradeable contract).
The contract creation code would need to be the same on every chain, so the chain specific constructor would need to be moved to an `initializer` that would need to be called after the contract is deployed.

You could create a deployer contract using the ideas from ProxyFactory:

https://github.com/OpenZeppelin/openzeppelin-sdk/blob/master/packages/lib/contracts/upgradeability/ProxyFactory.sol#L81

So a little bit convoluted but that is because of the chain specific information.

**Comment by Ro5s** [comment]
thanks for notes @abcoathup this helps a lot! 

I got a start on a lean deployer contract that seems to work with computing address for WETH10. Think this might get us there: https://github.com/wETH-v2/wETH-v2/pull/22

**Comment by albertocuestacanada** [comment]
If CREATE2 is too hard, we can just create a throwaway deployer account and deploy WETH10

**Comment by albertocuestacanada** [comment]
Sorry, clicked wrong button from phone.

**Comment by albertocuestacanada** [comment]
Fixed in #72
