### ISSUE TITLE
add gas tests for every function

### ISSUE THREAD

**Issue by moodysalem** [WETH10/WETH10#59]
test the gas efficiency of every function

**Comment by albertocuestacanada** [comment]
This is done in every PR with "before" and "after" comments.

**Comment by moodysalem** [comment]
@albertocuestacanada do you mean done manually in the github pr comments?

diffing it via unit tests is much more readable imo

**Comment by albertocuestacanada** [comment]
Yeah, the current method is quite crude. Do you have an example of what you are proposing?

**Comment by moodysalem** [comment]
https://github.com/Uniswap/uniswap-lib/blob/master/test/FixedPoint.spec.ts#L260

**Comment by albertocuestacanada** [comment]
What would be the point of encoding exact gas costs as tests? It looks like maintenance hell.

I think that integrating [eth-gas-reporter](https://hardhat.org/plugins/buidler-gas-reporter.html) as a CI check in the repo would be a better choice.

[Here](https://github.com/yieldprotocol/fyDai/pull/382/checks?check_run_id=1331866581) we just run it, which is useful because you have a gas usage record of each commit and you can do analysis on that.

A CI check that gas usage increases need to be signed off might be even better (or not, overhead). I don't know yet how to set up CI on github, though.

**Comment by moodysalem** [comment]
> What would be the point of encoding exact gas costs as tests? It looks like maintenance hell.

So you have to ack each change that affects gas prices and the changes are available via diffs. We use this mocha plugin so we don't have to copy paste the numbers, just run with `UPDATE_SNAPSHOT=1`
https://www.npmjs.com/package/mocha-chai-jest-snapshot

Integrating it into CI has the same effect. Either way, the point is to programmatically commit how much gas different operations take so you do not accidentally make it worse.

**Comment by albertocuestacanada** [comment]
@k06a, do you feel brave enough to setup [codechecks.io](https://app.codechecks.io)?

That's how you get [this](https://github.com/Synthetixio/synthetix/pull/670/checks?check_run_id=1005666516).
