### ISSUE TITLE
Consider alternative to ERC677

### ISSUE THREAD

**Issue by wighawag** [WETH10/WETH10#73]
ERC677 is not well documented (for example the ERC currently mentioned emitting special Transfer event, which is a really bad idea) and transferAndCall require special support from receiver

Here are some discussion on alternatives : https://ethereum-magicians.org/t/about-677-and-other-functions-on-top-of-erc20/4589

**Comment by albertocuestacanada** [comment]
I wouldn't mind taking the `approveAndCall` approach, as it seems to be an easier transition from the current `approve` + `transferFrom` model. I'm open to consider using EIP-2771 as well.

I'm a bit more sceptical on TransferGateways, mostly because I'm not familiar with the pattern and I don't immediately grasp it.

Please feel free to draft a PR and we will discuss the pros and cons on the code.

**Comment by albertocuestacanada** [comment]
I sent you an invite so that you can open the PR directly in this repo.
