### ISSUE TITLE
Dead code in WETH10

### ISSUE THREAD

**Issue by PwC-SCA** [WETH10/WETH10#97]
The `WETH10` implementation contains dead code:

https://github.com/WETH10/WETH10/blob/269b367e49bbf58bfb722ea1419743180ef0cea4/contracts/WETH10.sol#L381-L388

This code can never execute successfully as `to == address(0)` so that the Solidity-integrated check will fail for the following line:

https://github.com/WETH10/WETH10/blob/269b367e49bbf58bfb722ea1419743180ef0cea4/contracts/WETH10.sol#L391

Dead code in principle is not bad, it just fails later than it should and could confuse integrators.

**Comment by albertocuestacanada** [comment]
When coding WETH10 we took a radical approach to gas savings. Any gas that could be saved, would. The rationale is that the contract might become a backbone of DeFi and tiny gas costs ballon into huge collective amounts due to massive use.

While it's true that it would be nicer to fail early, I think we can live with the cheaper implementation.
